### ISSUE TITLE
0.12 support

### ISSUE THREAD

**Issue by Dyllaann** [claranet/jinjaform#28]
With HCL 1.12 becoming more adapted in public plugins, Jinjaform is one of the last things that is keeping me from updating to 0.12.

Are there any plans on updating Jinjaform to 0.12?

(I did see your comment in #27 about pretf, but that would mean a pretty big rewrite of our Terraform repository is needed. 
More importantly, It does not seem to offer the hierarchical project structure support that Jinjaform offers, which our project makes great use of.)

**Comment by raymondbutcher** [comment]
Hi @Dyllaann. We don't currently have any plans to update Jinjaform to support 0.12.x.

Pretf can do pretty much everything Jinjaform does except for the git checks (which you could easily add yourself with a custom Pretf workflow), and the Jinja2 template rendering.

The "flatten" example of Pretf shows how to have the same hierarchical project structure by using a `pretf.workflow.py` file. Compare these 2 examples from Jinaform and Pretf:

* https://github.com/claranet/jinjaform/tree/master/example
* https://github.com/raymondbutcher/pretf/tree/master/examples/flatten

If you're heavily using the Jinja2 template feature of Jinjaform, then there might be a bit of work to convert them into Python files for Pretf to generate the same Terraform configuration.

If you do decide to switch, feel free to raise issues/questions here or in the Pretf repository (and mention me if you need to grab my attention) and I'll help.
